---
name: "Shikimori"
guid: "7edb2a28-5b8a-4fe8-ae11-d941315eb862"
imageUrl: "https://shikimori.one/assets/layouts/l-top_menu-v2/glyph.svg"
version: "4.0.0.0"
targetAbi: "10.10.3"
framework: "net8.0"
owner: "te9c"
overview: "Metadata provider for Shikimori"
description: "Adds metadata for anime tv and movies"
category: "Metadata"
artifacts:
- "Jellyfin.Plugin.Shikimori.dll"
- "Newtonsoft.Json.dll"
changelog: >
  Fixed bugs
